application:
  dev:
    debug: False
    log:
      disable_file_log_stream: true
      log_folder: "logs"
    gym_server:
      protocol: https
      server_ip: "75.140.90.211"
      secured_port: 8443
    user:
      api_token: "OFFWORLD_GYM_ACCESS_TOKEN"
